# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_project.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewProjectDialog(object):
    def setupUi(self, NewProjectDialog):
        NewProjectDialog.setObjectName("NewProjectDialog")
        NewProjectDialog.resize(653, 296)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NewProjectDialog.sizePolicy().hasHeightForWidth())
        NewProjectDialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        NewProjectDialog.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(NewProjectDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 130, 511, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.save_location_layout = QtWidgets.QGridLayout(self.verticalLayoutWidget)
        self.save_location_layout.setContentsMargins(0, 0, 0, 0)
        self.save_location_layout.setObjectName("save_location_layout")
        self.save_location_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_location_line.sizePolicy().hasHeightForWidth())
        self.save_location_line.setSizePolicy(sizePolicy)
        self.save_location_line.setObjectName("save_location_line")
        self.save_location_layout.addWidget(self.save_location_line, 1, 0, 2, 1)
        self.reference_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reference_button.sizePolicy().hasHeightForWidth())
        self.reference_button.setSizePolicy(sizePolicy)
        self.reference_button.setAutoDefault(False)
        self.reference_button.setDefault(False)
        self.reference_button.setFlat(False)
        self.reference_button.setObjectName("reference_button")
        self.save_location_layout.addWidget(self.reference_button, 1, 1, 2, 1)
        self.save_location_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.save_location_label.setFont(font)
        self.save_location_label.setObjectName("save_location_label")
        self.save_location_layout.addWidget(self.save_location_label, 0, 0, 1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(NewProjectDialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(70, 50, 511, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.project_name_layout = QtWidgets.QGridLayout(self.verticalLayoutWidget_2)
        self.project_name_layout.setContentsMargins(0, 0, 0, 0)
        self.project_name_layout.setObjectName("project_name_layout")
        self.project_name_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.project_name_line.setObjectName("project_name_line")
        self.project_name_layout.addWidget(self.project_name_line, 1, 0, 2, 1)
        self.project_name_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.project_name_label.setFont(font)
        self.project_name_label.setObjectName("project_name_label")
        self.project_name_layout.addWidget(self.project_name_label, 0, 0, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(NewProjectDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(360, 230, 221, 44))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.buttons_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.buttons_layout.setContentsMargins(0, 0, 0, 0)
        self.buttons_layout.setObjectName("buttons_layout")
        self.cancel_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel_button.setAutoDefault(False)
        self.cancel_button.setObjectName("cancel_button")
        self.buttons_layout.addWidget(self.cancel_button)
        self.create_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.create_button.setCheckable(False)
        self.create_button.setChecked(False)
        self.create_button.setAutoDefault(True)
        self.create_button.setFlat(False)
        self.create_button.setObjectName("create_button")
        self.buttons_layout.addWidget(self.create_button)

        self.retranslateUi(NewProjectDialog)
        QtCore.QMetaObject.connectSlotsByName(NewProjectDialog)
        NewProjectDialog.setTabOrder(self.project_name_line, self.save_location_line)
        NewProjectDialog.setTabOrder(self.save_location_line, self.reference_button)
        NewProjectDialog.setTabOrder(self.reference_button, self.cancel_button)
        NewProjectDialog.setTabOrder(self.cancel_button, self.create_button)

    def retranslateUi(self, NewProjectDialog):
        _translate = QtCore.QCoreApplication.translate
        NewProjectDialog.setWindowTitle(_translate("NewProjectDialog", "Dialog"))
        self.reference_button.setText(_translate("NewProjectDialog", "参照"))
        self.save_location_label.setText(_translate("NewProjectDialog", "保存先"))
        self.project_name_label.setText(_translate("NewProjectDialog", "プロジェクト名"))
        self.cancel_button.setText(_translate("NewProjectDialog", "キャンセル"))
        self.create_button.setText(_translate("NewProjectDialog", "作成"))

